on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # https://github.com/marketplace/actions/checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Zip files
        run: |
          zip -r ${{ steps.get_version.outputs.VERSION }}.zip *.css module.json LICENSE scripts templates assets lang
      - name: Create and Upload Release
        # https://github.com/marketplace/actions/gh-release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: ${{ steps.get_version.outputs.VERSION }}.zip

